Errors now output in red

diff --git a/global_functions b/global_functions
--- a/global_functions
+++ b/global_functions
@@ -9,7 +9,7 @@ debug () {
 }
 
 error () {
-	echo "Error: $@" >&2
+	echo -e "\033[91mError: $@\033[0m" >&2
 }
 
 die () {
