Major stylistic cleanup via Shellcheck - mainly for globbing prevention

diff --git a/global_functions b/global_functions
--- a/global_functions
+++ b/global_functions
@@ -4,16 +4,16 @@
 debug () {
 	if [ -z "$_IN_PRODUCTION" ];
 	then
-		echo "DEBUG: $@" >&2
+		echo "DEBUG: $*" >&2
 	fi
 }
 
 error () {
-	echo -e "\033[91mError: $@\033[0m" >&2
+	echo -e "\033[91mError: $*\033[0m" >&2
 }
 
 die () {
-	error "$@"
+	error "$*"
 	exit 1
 }
 
