Added `useradd`

diff --git a/nggroup b/nggroup
--- a/nggroup
+++ b/nggroup
@@ -6,15 +6,18 @@ debug() { echo "$@" 1>&2; }
 HTPASS_DIR=.
 SITES_DIR=$HTPASS_DIR/sites
 SITES_DIR_FORMAT="$SITES_DIR/.%s.rules"
+USER_DIR=$HTPASS_DIR/users
+USER_DIR_FORMAT="$USER_DIR/%s"
+TMP_FILE=/tmp/nggrouptmp
 
 if [ "$(id -u)" != "0" ];
 then
     echo "Error; Must run as root."
 fi
 
-mkdir -p $HTPASS_DIR 
-mkdir -p $SITES_DIR 
-
+mkdir -p $HTPASS_DIR
+mkdir -p $SITES_DIR
+mkdir -p $USER_DIR
 
 case $1 in
     siteadd )
@@ -23,5 +26,19 @@ case $1 in
     sitedel )
 	rm $(printf $SITES_DIR_FORMAT $2)
 	;;
+
+    
+    useradd )
+	file=$(printf $USER_DIR_FORMAT $2)
+	contents=$(htpasswd -nb $2 $3)
+	if [ -e $file ];
+	then
+	    echo "Error: user already exists."
+	    exit 1
+	fi
+
+	echo $contents > $file
+	;;
+
 esac
 
