Both (site|group)mod now use same file formats and structure. Tests amended to reflect this

diff --git a/nggroup b/nggroup
--- a/nggroup
+++ b/nggroup
@@ -50,47 +50,7 @@ site () {
 	    rm $site_file
 	    ;;
 	sitemod )
-	    site_file=$(printf $SITES_DIR_FORMAT $2)
-	    group_file=$(printf $GROUP_DIR_FORMAT $4)
-	    if [ ! -e $group_file ];
-	    then
-		echo "Error: Group does not exist"
-		exit 1
-	    fi
-
-	    if [ ! -e $site_file ];
-	    then
-		echo "Error: Site does not exist"
-		exit 1
-	    fi
-
-	    # check if the group exists in the site's rules
-	    grep $4 $site_file > /dev/null
-	    group_in_site=$?
-
-	    case $3 in
-		a )
-		    # check if already there
-		    if [ 0 -eq $group_in_site ] ;
-		    then
-			# TODO: more meaningful messages - i.e. Group 'test'
-			echo "Error: Group already exists in site"
-			exit 1
-		    fi
-
-		    echo $4 >> $site_file
-		    ;;
-		d )
-		    if [ 1 -eq $group_in_site ] ;
-		    then
-			# TODO: rethink error codes?
-			echo "Error: Group does not exist in site"
-			exit 1
-		    fi
-
-		    sed -i /$4/d $site_file
-		    ;;
-	    esac
+	    mod_funct $site_file $3 $4 "Site"
 	    ;;
     esac
 }
@@ -145,69 +105,76 @@ group () {
 	    rm $group_file
 	    ;;
 	groupmod )
-	    if [ ! -e $group_file ];
-	    then
-		echo "Error: Group does not exist"
-		exit 1
-	    fi
-
-	    local context
-	    local context_file
-	    local context_dir_format
-	    local context_rule_format
-	    local context_friendly
-
-	    context=$(echo $4 | cut -c 2-)
-
-	    case $4 in
-		u* )
-		    context_dir_format=$USER_DIR_FORMAT
-		    context_rule_format=$USER_RULE_FORMAT
-		    context_friendly=User
-		    ;;
-		g* )
-		    context_dir_format=$GROUP_DIR_FORMAT
-		    context_rule_format=$GROUP_RULE_FORMAT
-		    context_friendly=Group
-		    ;;
-	    esac
-
-	    context_file=$(printf $context_dir_format $context)
-	    context_insert=$(printf $context_rule_format $context)
-	    
-	    if [ ! -e $context_file ];
-	    then
-		printf "Error: %s does not exist.\n" $context_friendly
-		exit 1
-	    fi
-	    
-	    grep $context $group_file > /dev/null
-	    context_in_file=$?
-
-	    case $3 in
-		a )
-		    if [ 0 -eq $context_in_file ];
-		    then
-			printf "Error: %s is already part of the group.\n" $context_friendly
-			exit 1
-		    else
-			echo $context_insert >> $group_file
-		    fi
-		    ;;
-		d )
-		    if [ 0 -eq $context_in_file ];
-		    then
-			sed -i /$context_insert/d $group_file
-		    else
-			printf "Error: %s does not exist in the group.\n" $context_friendly
-			exit 1
-		    fi
-		    ;;
-	    esac
-
+	    mod_funct $group_file $3 $4 "Group"
 	    ;;
     esac
 }
+
+
+mod_funct () {
+    if [ ! -e $1 ];
+    then
+	printf "> Error: %s does not exist\n" $4
+	exit 1
+    fi
+
+    local context
+    local context_file
+    local context_dir_format
+    local context_rule_format
+    local context_friendly
+
+    context=$(echo $3 | cut -c 2-)
+
+    case $3 in
+	u* )
+	    context_dir_format=$USER_DIR_FORMAT
+	    context_rule_format=$USER_RULE_FORMAT
+	    context_friendly=User
+	    ;;
+	g* )
+	    context_dir_format=$GROUP_DIR_FORMAT
+	    context_rule_format=$GROUP_RULE_FORMAT
+	    context_friendly=Group
+	    ;;
+    esac
+
+    context_file=$(printf $context_dir_format $context)
+    context_insert=$(printf $context_rule_format $context)
+
+    if [ ! -e $context_file ];
+    then
+	printf "Error: %s does not exist.\n" $context_friendly
+	exit 1
+    fi
+
+    grep $context $1 > /dev/null
+    context_in_file=$?
+
+    case $2 in
+	a )
+	    if [ 0 -eq $context_in_file ];
+	    then
+		printf "Error: %s is already part of the group.\n" $context_friendly
+		exit 1
+	    else
+		echo $context_insert >> $1
+	    fi
+	    ;;
+	d )
+	    if [ 0 -eq $context_in_file ];
+	    then
+		sed -i /$context_insert/d $1
+	    else
+		printf "Error: %s does not exist in the group.\n" $context_friendly
+		exit 1
+	    fi
+	    ;;
+    esac
+
+}
+
+
 
 case $1 in
     site* )
